/**
 * GENERATED by e2e/gen-map-fixture.mjs. Do not edit by hand.
 *
 * A real esbuild-minified bundle and its source map. Used to test the VLQ
 * decoder against output a bundler actually produces.
 */

export const MINIFIED = "export function computeTotal(r){let e=0;for(const t of r){if(t.price<0)throw new RangeError(\"negative price\");e+=t.price*t.quantity}return e}\n";

export const SOURCE_MAP = {
  "version": 3,
  "sources": [
    "src/checkout.ts"
  ],
  "sourcesContent": [
    "export function computeTotal(items) {\n  let total = 0;\n  for (const item of items) {\n    if (item.price < 0) {\n      throw new RangeError(\"negative price\");\n    }\n    total += item.price * item.quantity;\n  }\n  return total;\n}\n"
  ],
  "mappings": "AAAO,gBAAS,aAAaA,EAAO,CAClC,IAAIC,EAAQ,EACZ,UAAWC,KAAQF,EAAO,CACxB,GAAIE,EAAK,MAAQ,EACf,MAAM,IAAI,WAAW,gBAAgB,EAEvCD,GAASC,EAAK,MAAQA,EAAK,QAC7B,CACA,OAAOD,CACT",
  "names": [
    "items",
    "total",
    "item"
  ]
};
