/**
 * Regenerates `src/stack/fixtures.ts` from real browser engines.
 *
 * Run with: pnpm capture:stacks
 *
 * The parser's test fixtures must come from the engines themselves. A
 * hand-written stack tests the parser against the same assumption that
 * produced it, and the formats differ in details nobody remembers correctly:
 * whether there is a header line, whether anonymous frames carry an empty
 * function slot, how closures are suffixed.
 *
 * The page is served over HTTP from a real `.js` file rather than injected
 * with `setContent`. That matters: injected content produces `<anonymous>` and
 * `about:blank` as file names, which no production stack ever contains, and
 * fixtures built from it would exercise paths the parser never meets in
 * practice while missing the ones it does.
 *
 * Committing the generated file means CI needs no browsers to run unit tests;
 * this script only runs when someone wants to refresh them.
 */
import { chromium, webkit, firefox, type Browser } from "@playwright/test";
import { createServer } from "node:http";
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import type { AddressInfo } from "node:net";

const HERE = dirname(fileURLToPath(import.meta.url));

const SCRIPT = `function innerThrow() { throw new TypeError("watchfire fixture failure"); }
function middleCall() { innerThrow(); }
function handleClick() { middleCall(); }
function anonymousCaller() { (function () { handleClick(); })(); }
window.__capture = function () {
  try { anonymousCaller(); } catch (e) { return e.stack || String(e); }
  return null;
};
`;

const HTML = `<!doctype html><html><head><script src="/app.js"></script></head><body></body></html>`;

const ENGINES: Array<[string, () => Promise<Browser>]> = [
  ["chromium", () => chromium.launch()],
  ["webkit", () => webkit.launch()],
  ["firefox", () => firefox.launch()],
];

async function startServer(): Promise<{ url: string; close: () => Promise<void> }> {
  const server = createServer((request, response) => {
    if (request.url === "/app.js") {
      response.writeHead(200, { "content-type": "text/javascript" });
      response.end(SCRIPT);
      return;
    }
    response.writeHead(200, { "content-type": "text/html" });
    response.end(HTML);
  });

  await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
  const { port } = server.address() as AddressInfo;

  return {
    url: `http://127.0.0.1:${port}/`,
    close: () => new Promise<void>((resolve) => server.close(() => resolve())),
  };
}

async function capture(launch: () => Promise<Browser>, url: string): Promise<string> {
  const browser = await launch();
  try {
    const page = await browser.newPage();
    await page.goto(url);
    const stack = await page.evaluate(() =>
      (window as unknown as { __capture(): string | null }).__capture(),
    );
    if (typeof stack !== "string" || stack.length === 0) {
      throw new Error("engine produced no stack");
    }
    return stack;
  } finally {
    await browser.close();
  }
}

/**
 * The port varies per run, so it is replaced with a placeholder the fixture
 * can assert against. Without this every capture would produce a diff.
 */
function stabilize(stack: string, url: string): string {
  const origin = new URL(url).origin;
  return stack.replaceAll(origin, "http://localhost:9999");
}

async function main(): Promise<void> {
  const server = await startServer();
  const captured: Record<string, string> = {};
  try {
    for (const [name, launch] of ENGINES) {
      process.stdout.write(`capturing ${name}... `);
      captured[name] = stabilize(await capture(launch, server.url), server.url);
      process.stdout.write("ok\n");
    }
  } finally {
    await server.close();
  }

  const body = Object.entries(captured)
    .map(
      ([engine, stack]) => `  ${engine}: {
    stack: ${JSON.stringify(stack)},
    expectedTopFunction: "innerThrow",
    expectedFileFragment: "/app.js",
  },`,
    )
    .join("\n");

  const file = `/**
 * GENERATED by e2e/capture-stacks.ts. Do not edit by hand.
 *
 * Real \`error.stack\` output from each engine, thrown from the same call chain
 * (anonymousCaller -> an anonymous IIFE -> handleClick -> middleCall ->
 * innerThrow) in a script served over HTTP. Refresh with
 * \`pnpm capture:stacks\` after a browser update.
 */

export interface EngineStack {
  stack: string;
  expectedTopFunction: string;
  expectedFileFragment: string;
}

export const ENGINE_STACKS: Record<string, EngineStack> = {
${body}
};
`;

  const out = join(HERE, "..", "src", "stack", "fixtures.ts");
  await writeFile(out, file, "utf8");
  process.stdout.write(`wrote ${out}\n`);
}

main().catch((error: unknown) => {
  process.stderr.write(`${error instanceof Error ? error.stack : String(error)}\n`);
  process.exitCode = 1;
});
