/**
 * GENERATED by e2e/capture-stacks.ts. Do not edit by hand.
 *
 * Real `error.stack` output from each engine, thrown from the same call chain
 * (anonymousCaller -> an anonymous IIFE -> handleClick -> middleCall ->
 * innerThrow) in a script served over HTTP. Refresh with
 * `pnpm capture:stacks` after a browser update.
 */

export interface EngineStack {
  stack: string;
  expectedTopFunction: string;
  expectedFileFragment: string;
}

export const ENGINE_STACKS: Record<string, EngineStack> = {
  chromium: {
    stack: "TypeError: watchfire fixture failure\n    at innerThrow (http://localhost:9999/app.js:1:31)\n    at middleCall (http://localhost:9999/app.js:2:25)\n    at handleClick (http://localhost:9999/app.js:3:26)\n    at http://localhost:9999/app.js:4:45\n    at anonymousCaller (http://localhost:9999/app.js:4:62)\n    at window.__capture (http://localhost:9999/app.js:6:9)\n    at eval (eval at evaluate (:311:30), <anonymous>:1:12)\n    at UtilityScript.evaluate (<anonymous>:313:16)\n    at UtilityScript.<anonymous> (<anonymous>:1:44)",
    expectedTopFunction: "innerThrow",
    expectedFileFragment: "/app.js",
  },
  webkit: {
    stack: "innerThrow@http://localhost:9999/app.js:1:44\nmiddleCall@http://localhost:9999/app.js:2:35\nhandleClick@http://localhost:9999/app.js:3:36\n@http://localhost:9999/app.js:4:56\nanonymousCaller@http://localhost:9999/app.js:4:62\n@http://localhost:9999/app.js:6:24\n@\nevaluate@\n@",
    expectedTopFunction: "innerThrow",
    expectedFileFragment: "/app.js",
  },
  firefox: {
    stack: "innerThrow@http://localhost:9999/app.js:1:31\nmiddleCall@http://localhost:9999/app.js:2:25\nhandleClick@http://localhost:9999/app.js:3:26\nanonymousCaller/<@http://localhost:9999/app.js:4:45\nanonymousCaller@http://localhost:9999/app.js:4:62\nwindow.__capture@http://localhost:9999/app.js:6:9\n@debugger eval code line 311 > eval:1:12\nevaluate@debugger eval code:313:16\n@debugger eval code:1:44\n@debugger eval code:1:62\n",
    expectedTopFunction: "innerThrow",
    expectedFileFragment: "/app.js",
  },
};
